### ISSUE TITLE
AUTHKEY not working for me

### ISSUE THREAD

**Issue by tzabbi** [Hackebein/docker-garrysmod#17]
Thanks for the possibility to have a GM server as a docker container.

Currently I encounter to the issue that my AUTHKEY seems not to work.

```
ttt-server  | GLST can't be created! Check your AUTHKEY, GLSTAPP and account requirements
```

I generated the API key again but woth the same issue.

Do you know if I do something wrong?

**Comment by Hackebein** [comment]
It were working with my automated tests and on my own server today.

Could you please execute the following command and share the result with me?

`curl -s -d "key=<yourAPIkey>&appid=4000&memo=TEST" 'https://api.steampowered.com/IGameServersService/CreateAccount/v1/'`

Attention! This response contains a secret. Please remove your test entry at https://steamcommunity.com/dev/managegameservers before posting your response.

**Comment by tzabbi** [comment]
Got an empty response: `{"response":{}}`

EDIT:
i used postman and got the following http response:

`Forbidden Access is denied. Retrying will not help. Please verify your key=  parameter.`

**Comment by tzabbi** [comment]
I fixed it! I have to be use the 2FA with the steam mobile app. After I enabled it, everything works fine.

Sry for the stupid mistake...
