### ISSUE TITLE
Physic glitches in counter strike maps

### ISSUE THREAD

**Issue by TheFehr** [Hackebein/docker-garrysmod#3]
Hi I got everything to work. But on counterstricke maps the object's physic go haywheir. You can walk trough boxes and such.

**Comment by Hackebein** [comment]
Can you give me more information about this? What is the name of the map? I think i already have a clue what is going wrong.

**Comment by TheFehr** [comment]
One of them is rooftop for ttt

**Comment by TheFehr** [comment]
I think I'm missing the css files. Is there an easy way to add them?

**Comment by Hackebein** [comment]
> One of them is rooftop for ttt

Is there a workshop link for that map? Whats the complete map name?

> I think I'm missing the css files. Is there an easy way to add them?

Adding yes. Extend your starting parameter with: -e "APPS=4020,232330"
4020 is garrys mod (default)
232330 is css
But than comes the maybe more complex part ... mounting them. (checkout https://github.com/Hackebein/docker-garrysmod/tree/master/cfg) You could modify that file and mount/overwrite it with -v in your container

As i said before tell me more information and we could maybe fix that together for everyone.

**Comment by TheFehr** [comment]
Yes I'm pretty sure that'd be the fix. I had set up a gmod server quite some time ago. 

Maybe a env flag for adding the dependencies would be nice? 

I'll try your suggestion as soon as I can. And then I'll see if I can help you come up with a way to add a easy way for others?

**Comment by WasserEsser** [comment]
@TheFehr @Hackebein 

I came across the same issue today while setting up a server for a couple of friends. 

Specifying APPS=4020,232330 results in the following error:

> failed to dlopen /opt/steam/garrysmod/bin/server_srv.so error=/opt/steam/garrysmod/bin/server_srv.so Unknown something something SteamInternal_ContextInit

- To fix this with SteamCMD still downloading both servers, simply reverse the order to APPS=232330,4020. This will fix the issue of starting the server. 

- Next, to mount, specify the path in mount.cfg ("cstrike" "/opt/steam/cstrike") and make sure it along with the gamedepot in mountdepots.txt is uncommented.

docker build and my server is running just fine with fixed collision.

**Comment by Hackebein** [comment]
> * To fix this with SteamCMD still downloading both servers, simply reverse the order to APPS=232330,4020. This will fix the issue of starting the server.

I noticed that in my tests yesterday, too. Thanks for confirming.

> * Next, to mount, specify the path in mount.cfg ("cstrike" "/opt/steam/cstrike") and make sure it along with the gamedepot in mountdepots.txt is uncommented.

I'm searching for a very comfortable way to do that rn. I hope i can release that soon

**Comment by Hackebein** [comment]
CSS content is automatically downloaded and mountet now.
Can you please check that it is working and send feedback?

For me it's working, tested with map: https://steamcommunity.com/sharedfiles/filedetails/?id=266354490

**Comment by TheFehr** [comment]
Yes now it works like a charm. Thanks alot @WasserEsser and @Hackebein
