### ISSUE TITLE
Steamcmd offline

### ISSUE THREAD

**Issue by TheFehr** [Hackebein/docker-garrysmod#5]
Since yesterday I receive this error on docker start:

!!! Fatal Error: Steamcmd needs to be online to update.	 Please confirm your network connection and try again.

It seems my docker just doesn't want to talk to the internet anymore. And I have no idea why. My host has no problem to connect to the internet.
And a simple alpine:latest docker container also doesn't have any problem connecting to the internet.

**Comment by Hackebein** [comment]
Can you serve more details? ex. Host OS, docker versions, your docker container run command or docker-compose file.

**Comment by TheFehr** [comment]
It must be something with my setup because I just ran a plain ```docker run --rm -it hackebein/garrysmod bash``` and it did not have a problem to connect to steamcmd

**Comment by TheFehr** [comment]
version: '3.3'

services:
    garrysmod:
        volumes:
            - '/home/AMP/custom_server/server_data/ttt:/opt/steam'
        ports:
            - '27015:27015/tcp'
            - '27015:27015/udp'
        environment:
            - MAP=ttt_minecraft_b5
            - AUTHKEY=_MYAUTHKEY_
            - GAMEMODE=terrortown
            - WORKSHOPCOLLECTIONID=_THECOLLECTIONID_
        container_name: ttt
        image: hackebein/garrysmod

**Comment by Hackebein** [comment]
> It must be something with my setup because I just ran a plain `docker run --rm -it hackebein/garrysmod bash` and it did not have a problem to connect to steamcmd

How about recreating the container?

**Comment by TheFehr** [comment]
Now I'm really confused I moved away the content in the volume. And then copied the essential config and such back to the newly downloaded one and works like a charm.
