### ISSUE TITLE
FastDL

### ISSUE THREAD

**Issue by Snavellet** [Hackebein/docker-garrysmod#7]
Is there a FastDL environment variable?

**Comment by Hackebein** [comment]
Unfortunately not. Now after you asking for that I'm thinking about to implement that.

**Comment by Snavellet** [comment]
Alright

**Comment by Hackebein** [comment]
I reopen this issue as a reminder for me to implement it soon

**Comment by Hackebein** [comment]
WorkshopDL env is added. Maybe that helps you already. set it to your collection for advice clients to download it before connect to server.

FastDL is coming soon

**Comment by Snavellet** [comment]
Alright, nice job.

**Comment by Hackebein** [comment]
After investing a lot of time into FastDL. The possibilities are too diverse and especially to implement this feature. I hope WorkshopDL feature is good enough.
