### ISSUE TITLE
Caching entire Gmod/Workshop installation?

### ISSUE THREAD

**Issue by dsxsh** [Hackebein/docker-garrysmod#8]
Hey, is it possible to have the entire gmod/addon installs be in a mounted folder? 

Kind of a pain to have them re-download every time the container exits and starts back up.

**Comment by dsxsh** [comment]
I assume it would be something similar to: `-v ./overlay:/opt/overlay \`

**Comment by dsxsh** [comment]
I guess what I'm really looking for is a way to persist the docker volume and hand it back to the container that created it.

**Comment by Hackebein** [comment]
>Kind of a pain to have them re-download every time the container exits and starts back up.

If you would reuse volumes you wouldn't have the problem.

What you searching for is making the [working directory/volume](https://github.com/Hackebein/docker-srcds/blob/master/Dockerfile#L60) persistent with `-v $(pwd)/workdir:/opt/steam` or you can reuse volumes.
