### ISSUE TITLE
no TTY (-t) detected

### ISSUE THREAD

**Issue by tomatosoupcan** [Hackebein/docker-garrysmod#9]
Starting with a recent update my container will no longer start, giving the error:
no TTY (-t) detected
Steam needs it. Exit.

**Comment by tomatosoupcan** [comment]
Nevermind I have fixed it my dude

**Comment by Hackebein** [comment]
Sorry that it effects you in a negative way. I add this reminder that remembers people to add -t (for tty) and -i (for interactive) for there setups. without them you can't see most of the errors because they are in buffer. Maybe bringing up a better solution in the future.
